### ISSUE TITLE
你这个库，怎么安装magisk里。新手不太懂，

### ISSUE THREAD

**Issue by ss18873310** [victor141516/httpcanary-magisk#1]
希望维克多大佬出一下基础教程。谢谢。

**Comment by SabinLee** [comment]
下载它那个zip，在magisk里面安装模块的地方本地安装就行

**Comment by snowman** [comment]
> 下载它那个zip，在magisk里面安装模块的地方本地安装就行

安装成功后可以在设置中显示, 但是 `HttpCanary 3.3.5` 版本打开还是提示安装`root certificate`

**Comment by victor141516** [comment]
Hey guys sorry for not responding here. If I understand correctly, you want to know how to use this.

Well, it's not as easy as just installing the zip. First you need to follow this guide, as described [here](https://www.reddit.com/r/androidroot/comments/n1mej9/guide_how_to_use_httpcanary_and_decrypt_https_on/):
 - From `/data/data/com.guoshi.httpcanary.premium/cache` copy `HttpCanary.pem` and `HttpCanary.p12` to your phones accessible storage (such as Downloads or Documents).
 - Open up the 'settings app > Biometrics & Security > Other Security Settings > Install from device storage'.
 - Select 'CA certificate' and press 'Install anyway'.
 - Browse to `HttpCanary.pem` and install it.
 - On the 'Install from device storage' screen, now press 'VPN and app user certificate'
 - Browse to `HttpCanary.p12` and enter the password which is `HttpCanary` and do not modify the name.
 - On `/data/data/com.guoshi.httpcanary.premium/cache` create an empty file called `HttpCanary.jks`

Then you have to copy `HttpCanary.pem` to your computer and rename it to `87bc3517.0`. Clone this repo and replace the file `system/etc/security/cacerts/87bc3517.0` (**this path is in the repo, not on your android**) for the one you copied from your android.

Now you can zip the module again and flash it.

It a very manual process, but it can be automated in the module installation script. PR are appreciated :D

**Comment by victor141516** [comment]
I just updated everything. Now it's way easier to use this module. Instructions are on the readme. Any feedback is appreciated
