### ISSUE TITLE
There is a compatibility problem on magisk v26.1 .

### ISSUE THREAD

**Issue by p1v07** [victor141516/httpcanary-magisk#5]
the module not loaded on magisk v26.1.

**Comment by victor141516** [comment]
Hey! I upgraded to Magisk 26.1 and I could confirm the incompatibility message. I updated the module and it should work but it's still showing the incompatibility message.

I tried and removed the app and the module completely and install both again. The incompatibility message is still there, but the app works as expected.

Please try it and I think it'll also work for you. If that's not the case, just write a new comment here and I'll try to find a solution.

**Comment by p1v07** [comment]
Yes, it works. Thanks.
